### ISSUE TITLE
Mac builds fail

### ISSUE THREAD

**Issue by 8bitskull** [britzl/defold-clipboard#7]
I think some sort of security issue perhaps?

```
upload/clipboard/src/clipboard.cpp:5:9: warning: 'DLIB_LOG_DOMAIN' macro redefined [-Wmacro-redefined]
#define DLIB_LOG_DOMAIN LIB_NAME
```

Full log:
[log.txt](https://github.com/britzl/defold-clipboard/files/14167021/log.txt)

Defold 1.6.3

**Comment by 8bitskull** [comment]
Just managed to build without changing anything (I think). I believe the issue can be closed unless there is something interesting in the logs.

**Comment by britzl** [comment]
There was an error about disk space. We'll look into it. Closing this one though!

**Comment by JCash** [comment]
"upload/clipboard/src/clipboard.cpp:5:9: warning: 'DLIB_LOG_DOMAIN' macro redefined [-Wmacro-redefined]
#define DLIB_LOG_DOMAIN LIB_NAME"
Is just a warning that the define is already defined from the build system.

The superfluous define should be removed from this extension to avoid the warning.

**Comment by britzl** [comment]
> The superfluous define should be removed from this extension to avoid the warning.

Removed in https://github.com/britzl/defold-clipboard/commit/c159ca1bc6aeaff7f40e1cdb464384f97ab86c92
